export enum Category {
  TAX_OFFICE = 'TAX_OFFICE',
  CAR = 'CAR',
  FUEL = 'FUEL',
  OTHER_OFFICE = 'OTHER_OFFICE',
  WARRANTY = 'WARRANTY',
  HEALTH = 'HEALTH',
  COURT = 'COURT',
  ELECTRONICS = 'ELECTRONICS',
  CLOTHES = 'CLOTHES',
}
